name: encoding_tools
homepage: https://github.com/mehaase/encoding_tools

environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  convert: '^2.0.1'
  crypto: '^2.0.2'
  html_unescape: '^0.1.5'
  logging: '^0.11.3'

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
