name: encoding_tools
homepage: https://github.com/mehaase/encoding_tools

environment:
  sdk: '>=2.7.2 <3.0.0'

dependencies:
  convert: '^2.0.1'
  crypto: '^2.0.2'
  html_unescape: '^1.0.1'
  logging: '^0.11.3'

dev_dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.0.0

web:
  compiler:
    debug: dartdevc
